version: "3.8"

services:
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -h ${DB_HOST} -p ${DB_PORT} -U ${POSTGRES_USER}"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

  web:
    image: viktoriakosh/yamdb:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    ports:
     - "8000:8000"
    depends_on:
      - db
    #  db:
    #    condition: service_healthy
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/static/
      - media_value:/app/media/

    depends_on:
      - web

volumes:
  postgresql_volume:
  static_value:
  media_value:
